spring:
  rabbitmq:
    host: rabbitmq
#    port: 15672
#    addresses: 
    username: guest
    password: guest
#    virtualhost: 
#    dynamic: 
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"

eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:7070/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

authserver:
    hostname: auth-service
    port: 8551
    contextPath: /uaa

security:
  oauth2:
    resource:
      user-info-uri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/current
